import React, { useEffect, useState } from 'react';
import { request } from '../../services/api.js';
import { useCompany } from '../../context/CompanyContext.jsx';
import { exportToCSV } from '../../utils/csvExport.js';

export function MonthlyHours() {
  const { companies = [] } = useCompany();
  const [month, setMonth] = useState(() => { const today = new Date(); return `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`; }), [rows, setRows] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  useEffect(() => { let live = true; setLoading(true); setError(''); setRows([]); request(`/admin/timesheet-hours?month=${month}`).then(data => { if (live) setRows(data.employees); }).catch(err => { if (live) setError(err.message); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [month]);
  return <section className="company-access company-panel"><div className="company-actions"><div><h2>Approved hours for monthly payroll</h2><p>Hours are counted on the exact date worked, including timesheets spanning two months.</p></div><label>Payroll month<input type="month" required value={month} onChange={e => { if (e.target.value) setMonth(e.target.value); }} onInput={e => { if (e.target.value) setMonth(e.target.value); }} /></label><button disabled={loading || !rows.length} onClick={() => exportToCSV(rows.map(row => ({ 'Emp ID': row.employee_id, Name: row.employee_name, Company: companies.find(c => c.id === row.company_id)?.name || 'Legacy', Month: month, 'Approved hours': row.hours, 'Older timesheets needing allocation': row.unallocated_timesheets })), `Approved_Hours_${month}.csv`)}>Export hours</button></div>{error && <p role="alert" className="company-error company-notice">{error}</p>}<div className="company-table-wrap"><table><thead><tr><th>Employee</th><th>Company</th><th className="numeric">Approved hours</th><th>Allocation notes</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.employee_id}:${row.company_id}`}><td>{row.employee_name}<small>{row.employee_id}</small></td><td>{companies.find(c => c.id === row.company_id)?.name || 'Legacy record'}</td><td className="numeric">{row.hours.toFixed(2)}</td><td>{row.unallocated_timesheets ? `${row.unallocated_timesheets} older timesheets have no daily entries and are excluded from this total.` : 'Daily entries verified'}</td></tr>)}</tbody></table>{loading ? <p>Loading hours…</p> : !rows.length && <p>No approved hours for this month.</p>}</div></section>;
}
