import React, { useEffect, useState } from 'react';
import { request } from '../services/api.js';
import { RegisterWizard } from './RegisterWizard.jsx';

export function InvitationPage({ token, onNavigateLogin }) {
  const [invitation, setInvitation] = useState(null), [error, setError] = useState(''), [password, setPassword] = useState(''), [confirm, setConfirm] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  useEffect(() => { let live = true; request('/auth/invitation', { method: 'POST', body: { token } }).then(data => { if (live) setInvitation(data); }).catch(err => { if (live) setError(err.message); }); return () => { live = false; }; }, [token]);
  if (invitation?.role === 'employee') return <RegisterWizard invitation={{ ...invitation, token }} onNavigateLogin={onNavigateLogin} />;
  return <main className="company-access portal-public"><section className="company-panel"><h1>Corporate Employee Portal</h1><h2>{invitation ? 'Set up your domain admin account' : 'Your invitation'}</h2>{error && <p role="alert" className="company-notice company-error">{error}</p>}{message ? <p role="status">{message}</p> : invitation ? <form onSubmit={async event => { event.preventDefault(); if (password !== confirm) { setError('Passwords do not match.'); return; } setBusy(true); setError(''); try { const data = await request('/auth/invitation/accept', { method: 'POST', body: { token, password } }); setMessage(data.message); } catch (err) { setError(err.message); } finally { setBusy(false); } }}><p>{invitation.firstName} {invitation.lastName} · {invitation.email}</p><ul>{invitation.companies.map(c => <li key={c.id}>{c.name}</li>)}</ul><label>Password<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e => setPassword(e.target.value)} /></label><label>Confirm password<input type="password" autoComplete="new-password" required value={confirm} onChange={e => setConfirm(e.target.value)} /></label><button disabled={busy} className="company-primary">{busy ? 'Creating account…' : 'Create account'}</button></form> : !error && <p>Checking invitation…</p>}<button onClick={onNavigateLogin}>Back to sign in</button></section></main>;
}
