import React, { useEffect, useState } from 'react';
import { api, API_BASE, getAuthToken, request } from '../../services/api.js';
import { useCompany } from '../../context/CompanyContext.jsx';
import { exportToCSV } from '../../utils/csvExport.js';

const visas = ['H-1B', 'OPT', 'CPT', 'H-4 EAD', 'Green Card', 'US Citizen'];
const empty = { employee_id: '', employee_name: '', company_id: '', vendor_name: '', vendor_address: '', client_name: '', client_address: '', hourly_bill_rate: '', employee_rate: '', tax_percent: '', visa_type: 'H-1B', po_start_date: '', po_end_date: '' };
export function AdminVendorDetails() {
  const { companies = [], selected } = useCompany();
  const [vendors, setVendors] = useState([]), [employees, setEmployees] = useState([]), [search, setSearch] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [draft, setDraft] = useState(null), [editing, setEditing] = useState(null);
  async function load() { const [v, e] = await Promise.all([api.getAllVendorDetails(), api.getAllEmployees()]); setVendors(v.vendors); setEmployees(e.employees); }
  useEffect(() => { load().catch(err => setError(err.message)).finally(() => setLoading(false)); }, []);
  const rows = vendors.filter(v => `${v.employee_id} ${v.employee_name} ${v.vendor_name} ${v.client_name}`.toLowerCase().includes(search.toLowerCase()));
  const companyName = id => companies.find(c => c.id === id)?.name || 'Unassigned';
  async function upload(row, type, file) {
    if (!file) return; setBusy(true); setError(''); setMessage('');
    try { const body = new FormData(); body.append('document', file); await request(`/admin/vendors/${row._id || row.id}/files/${type}`, { method: 'POST', body }); await load(); setMessage(`${type.toUpperCase()} uploaded.`); } catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  async function download(row, type) {
    setError('');
    try { const response = await fetch(`${API_BASE}/admin/vendors/${row._id || row.id}/files/${type}`, { headers: { Authorization: `Bearer ${getAuthToken()}`, 'X-Company-Id': selected } }); if (!response.ok) throw new Error((await response.json()).error || 'Unable to download contract.'); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = row[`${type}_file`]; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (err) { setError(err.message); }
  }
  async function save(event) {
    event.preventDefault(); setBusy(true); setError('');
    try { const body = { ...draft }; if (editing) await api.updateVendorDetail(editing, body); else await api.createVendorDetail(body); setDraft(null); await load(); setMessage('Vendor placement saved.'); } catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  const employee = employees.find(e => e.employee_id === draft?.employee_id);
  const choices = companies.filter(c => c.enabled && employee?.company_ids?.includes(c.id));
  return <div className="company-access"><div className="company-actions"><div><h1>Vendor Placements</h1><p>Manage placements, agreements, and purchase orders.</p></div><button onClick={() => { setEditing(null); setDraft({ ...empty }); setError(''); }}>New</button><button disabled={!rows.length} onClick={() => exportToCSV(rows.map(v => ({ 'Emp ID': v.employee_id, Name: v.employee_name, Company: companyName(v.company_id), Vendor: v.vendor_name, Client: v.client_name, 'Visa Type': v.visa_type, MSA: v.msa_file || '', PO: v.po_file || '', 'PO Start Date': v.po_start_date || '', 'PO End Date': v.po_end_date || '' })), 'Vendor_Placements.csv')}>Export CSV</button></div>
    {error && <p role="alert" className="company-notice company-error">{error}</p>}{message && <p role="status" className="company-notice">{message}</p>}<label>Search<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Employee, vendor or client" /></label>
    <div className="company-panel company-table-wrap"><table><thead><tr>{['Employee', 'Company', 'Vendor', 'Client', 'Visa Type', 'MSA', 'PO to Upload', 'PO Start Date', 'PO End Date', 'Bill Rate', 'Employee Rate', 'Actions'].map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row._id || row.id}><td>{row.employee_name}<small>{row.employee_id}</small></td><td>{companyName(row.company_id)}</td><td>{row.vendor_name}</td><td>{row.client_name}</td><td>{row.visa_type}</td>{['msa', 'po'].map(type => <td key={type}>{row[`${type}_file`] && <button className="portal-link" onClick={() => download(row, type)}>{row[`${type}_file`]}</button>}<label className="portal-contract-input"><span className="sr-only">Upload {type.toUpperCase()} for {row.employee_name}</span><input type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" disabled={busy} onChange={e => { upload(row, type, e.target.files?.[0]); e.target.value = ''; }} /></label></td>)}<td>{row.po_start_date || '—'}</td><td>{row.po_end_date || '—'}</td><td className="numeric">{Number(row.hourly_bill_rate).toFixed(2)}</td><td className="numeric">{Number(row.employee_rate).toFixed(2)}</td><td><button onClick={() => { setEditing(row._id || row.id); setDraft({ ...empty, ...row }); setError(''); }}>Edit</button></td></tr>)}</tbody></table>{loading ? <p>Loading placements…</p> : !rows.length && <p>No placements match your search.</p>}</div>
    {draft && <div className="portal-dialog-backdrop"><section className="company-access portal-dialog" role="dialog" aria-modal="true" aria-labelledby="vendor-title"><h2 id="vendor-title">{editing ? 'Edit' : 'New'} Vendor Placement</h2>{error && <p role="alert" className="company-notice company-error">{error}</p>}<form onSubmit={save}><div className="company-grid"><label>Employee<select required disabled={Boolean(editing)} value={draft.employee_id} onChange={e => { const emp = employees.find(row => row.employee_id === e.target.value); setDraft({ ...draft, employee_id: e.target.value, employee_name: emp?.full_name || '', company_id: emp?.company_ids?.includes(selected) ? selected : emp?.company_ids?.length === 1 ? emp.company_ids[0] : '' }); }}><option value="">Select employee</option>{employees.map(emp => <option key={emp.employee_id} value={emp.employee_id}>{emp.employee_id} · {emp.full_name}</option>)}</select></label><label>Company<select required disabled={Boolean(editing && draft.company_id)} value={draft.company_id || ''} onChange={e => setDraft({ ...draft, company_id: e.target.value })}><option value="">Select company</option>{choices.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      {[['vendor_name', 'Vendor Name', true], ['vendor_address', 'Vendor Address'], ['client_name', 'Client Name', true], ['client_address', 'Client / Work Address']].map(([key, title, required]) => <label key={key}>{title}<input required={required} maxLength={1000} value={draft[key] || ''} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}<label>Visa Type<select value={draft.visa_type} onChange={e => setDraft({ ...draft, visa_type: e.target.value })}>{visas.map(v => <option key={v}>{v}</option>)}</select></label>
      {[['po_start_date', 'PO Start Date'], ['po_end_date', 'PO End Date']].map(([key, title]) => <label key={key}>{title}<input type="date" min={key === 'po_end_date' ? draft.po_start_date : undefined} value={draft[key] || ''} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}{[['hourly_bill_rate', 'Hourly Bill Rate'], ['employee_rate', 'Employee Rate'], ['tax_percent', 'Margin Tax Percentage']].map(([key, title]) => <label key={key}>{title}<input required type="number" min="0" max={key === 'tax_percent' ? 100 : undefined} step="0.01" value={draft[key] ?? ''} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}</div><p>Enter the approved margin tax percentage. Upload MSA and PO files from the placement row after saving (up to 8 MB).</p><div className="company-actions"><button type="button" disabled={busy} onClick={() => setDraft(null)}>Cancel</button><button disabled={busy} className="company-primary">{busy ? 'Saving…' : 'Save placement'}</button></div></form></section></div>}
  </div>;
}
