import React, { useCallback, useEffect, useState } from 'react';
import { request } from '../../services/api.js';
import { useCompany } from '../../context/CompanyContext.jsx';
import { exportToCSV } from '../../utils/csvExport.js';

export function AdminExpenses({ region }) {
  const { companies = [], selected } = useCompany();
  const [rows, setRows] = useState([]), [draft, setDraft] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const currency = region === 'India' ? 'INR' : 'USD';
  const money = value => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(value);
  const companyName = id => companies.find(c => c.id === id)?.name || id;
  const load = useCallback(() => request(`/admin/expenses?region=${region}`).then(data => setRows(data.expenses)), [region]);
  useEffect(() => { load().catch(err => setError(err.message)); }, [load]);
  return <div className="company-access"><div className="company-actions"><div><h1>{region} Expenses</h1><p>{rows.length} expenses · Total {money(rows.reduce((sum, row) => sum + row.amount, 0))}</p></div><button onClick={() => setDraft({ company_id: companies.some(c => c.id === selected) ? selected : '', date: new Date().toISOString().slice(0, 10), payee: '', category: '', amount: '', status: 'Pending', notes: '' })}>Add expense</button><button disabled={!rows.length} onClick={() => exportToCSV(rows.map(row => ({ Company: companyName(row.company_id), Date: row.date, Payee: row.payee, Category: row.category, Amount: row.amount, Currency: currency, Status: row.status, Notes: row.notes })), `${region}_Expenses.csv`)}>Export CSV</button></div>
    {error && <p role="alert" className="company-notice company-error">{error}</p>}
    <div className="company-panel company-table-wrap"><table><thead><tr>{['Date', 'Company', 'Payee', 'Category', `Amount (${currency})`, 'Status', 'Notes', 'Actions'].map(title => <th key={title} className={title.startsWith('Amount') ? 'numeric' : undefined}>{title}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.date}</td><td>{companyName(row.company_id)}</td><td>{row.payee}</td><td>{row.category}</td><td className="numeric">{money(row.amount)}</td><td>{row.status}</td><td>{row.notes || '—'}</td><td><button onClick={() => setDraft(row)}>Edit</button></td></tr>)}</tbody></table>{!rows.length && <p>No expenses recorded for this company workspace.</p>}</div>
    {draft && <div className="portal-dialog-backdrop"><section className="company-access portal-dialog" role="dialog" aria-modal="true" aria-labelledby="expense-title"><h2 id="expense-title">{draft.id ? 'Edit' : 'Add'} expense</h2>{error && <p role="alert" className="company-error company-notice">{error}</p>}<form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await request('/admin/expenses', { method: 'POST', body: { ...draft, region } }); await load(); setDraft(null); } catch (err) { setError(err.message); } finally { setBusy(false); } }}><div className="company-grid"><label>Company<select required disabled={Boolean(draft.id)} value={draft.company_id} onChange={e => setDraft({ ...draft, company_id: e.target.value })}><option value="">Select company</option>{companies.filter(c => c.enabled && (selected === 'all' || c.id === selected)).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{[['date', 'Date', 'date'], ['payee', 'Payee', 'text'], ['category', 'Category', 'text'], ['amount', `Amount (${currency})`, 'number']].map(([key, title, type]) => <label key={key}>{title}<input required type={type} min={type === 'number' ? '0.01' : undefined} step={type === 'number' ? '0.01' : undefined} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}<label>Status<select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value })}><option>Pending</option><option>Paid</option></select></label></div><label>Notes<textarea maxLength={2000} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label><div className="company-actions"><button type="button" disabled={busy} onClick={() => setDraft(null)}>Cancel</button><button disabled={busy} className="company-primary">Save expense</button></div></form></section></div>}
  </div>;
}
